config/routes.rb
Rails.application.routes.draw do
  get 'patients/index'

  resources :patients do
      resources :encounters
  end

  root 'patients#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  belongs_to :patient
  validates :visit_number, presence: true, 
                   length: { minimum: 1 }
  validates :admitted_at, presence: true 
end

app/models/patient.rb
class Patient < ApplicationRecord
   has_many :encounters
   validates :mrn, presence: true, 
                   length: { minimum: 1 }
   validates :first_name, presence: true, 
                   length: { minimum: 1 }
   validates :middle_name, presence: true, 
                   length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
   def index
      @patient = Patient.find(params[:patient_id])
      @encounters = @patient.encounters.all
   end

   def show
      @patient = Patient.find(params[:patient_id])
      @encounter = @patient.encounters.find(params[:id])
   end

   def new
      @patient = Patient.find(params[:patient_id])
      @encounter = Encounter.new 
   end

   def edit
      @patient = Patient.find(params[:patient_id])
      @encounter = @patient.encounters.find(params[:id])
   end

   def create
      #if params[:commit] == "Cancel"
      #   redirect_to patients_path
      #   return
      #end
      
      @patient = Patient.find(params[:patient_id])
      @encounter = @patient.encounters.create(encounter_params)

      if @encounter.save
         redirect_to patient_path(@patient)
      else
         render 'new'
      end
   end

private
      def encounter_params
         params.require(:encounter).permit(:visit_number, :admitted_at, :discharged_at, :location, :room, :bed)
      end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
   def index
      @patients = Patient.all
   end

   def show
      @patient = Patient.find(params[:id])
   end

   def new
      @patient = Patient.new
   end

   def edit
      @patient = Patient.find(params[:id])
   end

   def create
      if params[:commit] == "Cancel"
         redirect_to patients_path
         return
      end

      @patient = Patient.new(patient_params)

      if @patient.save
         redirect_to @patient
      else
         render 'new'
      end
   end

   def update
      @patient = Patient.find(params[:id])

      if params[:commit] == "Cancel"
         redirect_to @patient
         return
      end

      if @patient.update(patient_params)
         redirect_to @patient
      else
         render 'edit'
      end
   end

   def destroy
      @patient = Patient.find(params[:id])
      @patient.destroy

      redirect_to patients_path
   end

private
   def patient_params
      params.require(:patient).permit(:first_name, :middle_name, 
         :last_name, :weight, :height, :mrn)
   end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/encounters/_form.html.erb
<%= form_for([@patient, @patient.encounters.build]) do |f| %>
   
   <p>
      <%= f.label :visit_number, '*Visit Number:' %>
      <%= f.text_field :visit_number %>,
   
      <%= f.label :admitted_at, '*Admitted At:' %>
      <%= f.datetime_local_field :admitted_at %>,

      <%= f.label :discharged_at, 'Discharged At:' %>
      <%= f.datetime_local_field :discharged_at %>,

      <%= f.label :location, 'Location:' %>
      <%= f.text_field :location %>,

      <%= f.label :room, 'Room:' %>
      <%= f.select :room, (1..100).to_a %>,

      <%= f.label :bed, 'Bed:' %>
      <%= f.select :bed, (1..10).to_a %>
   </p>
   <p>
      <%= f.submit %>
   </p>
<% end %>

<%= link_to 'Back', @patient %>

app/views/encounters/edit.html.erb
<h2>Add an encounter:</h2>
<%= form_for([@patient, @patient.encounters.build]) do |f| %>
   
   <p>
      <%= f.label :visit_number, '*Visit Number:' %>
      <%= f.text_field :visit_number %>,
   
      <%= f.label :admitted_at, '*Admitted At:' %>
      <%= f.datetime_local_field :admitted_at %>,

      <%= f.label :discharged_at, 'Discharged At:' %>
      <%= f.datetime_local_field :discharged_at %>,

      <%= f.label :location, 'Location:' %>
      <%= f.text_field :location %>,

      <%= f.label :room, 'Room:' %>
      <%= f.select :room, (1..100).to_a %>,

      <%= f.label :bed, 'Bed:' %>
      <%= f.select :bed, (1..10).to_a %>
   </p>
   <p>
      <%= f.submit %>
   </p>
<% end %>

<%= link_to 'Back', @patient %>

app/views/encounters/new.html.erb
<h2>Add an encounter:</h2>
<%= form_for([@patient, @patient.encounters.build]) do |f| %>
   
   <p>
      <%= f.label :visit_number, '*Visit Number:' %>
      <%= f.text_field :visit_number %>,
   
      <%= f.label :admitted_at, '*Admitted At:' %>
      <%= f.datetime_local_field :admitted_at %>,

      <%= f.label :discharged_at, 'Discharged At:' %>
      <%= f.datetime_local_field :discharged_at %>,

      <%= f.label :location, 'Location:' %>
      <%= f.text_field :location %>,

      <%= f.label :room, 'Room:' %>
      <%= f.select :room, (1..100).to_a %>,

      <%= f.label :bed, 'Bed:' %>
      <%= f.select :bed, (1..10).to_a %>
   </p>
   <p>
      <%= f.submit %>
   </p>
<% end %>

<%= link_to 'Back', @patient %>

app/views/encounters/show.html.erb
<b>Visit Number:</b>
<%= @encounter.visit_number %>,

<b>Admitted At:</b>
<%= @encounter.admitted_at %>,

<strong>Discharged At:</strong>
<%= @encounter.discharged_at %>,

<b>Location:</b>
<%= @encounter.location %>,

<b>Room:</b>
<%= @encounter.room %>,

<b>Bed:</b>
<%= @encounter.bed %>

<br>
<br>
<%= link_to 'Back', @patient %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clinic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for @patient do |f| %>

<!-- check for / display errors
         need to have @article = Article.new in the ArticlesController
         else @article would be nil
-->
   <% if @article.errors.any? %>
      <div id="error_explanation">
         <h2>
            <%= pluralize(@article.errors.count, "error") %>
            prohibited this article from being saved:
         </h2>
         <ul>
            <% @article.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
   <% end %>
   
<!-- showing information -->
   <p>
      <!-- old... f.label :name, f.text_area :text -->
      <%= text_area_tag(:first_name, "First Name:") %>
      <%= text_area_tag(:middle_name, "Middle Name:") %>
      <%= text_area_tag(:last_name, "Last Name:") %>
      <%= number_field(:weight, :wt, in: 0.0..1000.0, step: 1.0) %>
      <%= number_field(:height, :ht, in: 1.0..1000.0, step: 1.0) %>
      <%= text_area_tag(:mrn, "MRN:") %>
   </p>
                
   <p>
      <%= f.submit %>
      <!-- < % = submit_tag("Cancel") %> -->
   </p>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<!-- < % = render 'form' %> -->
<%= form_for(@patient) do |f| %>
   <% if @patient.errors.any? %>
      <div id="error_explanation">
         <h2>
            <%= pluralize(@patient.errors.count, "error") %> 
            prohibited this data from being saved:
         </h2>
         <ul>
            <% @patient.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
   <% end %>
<!-- showing information -->
   <p>
      <!-- old... f.label :name, f.text_area :text -->
      <%= f.label :first_name, '*First Name:' %>
      <%= f.text_field :first_name %>,

      <%= f.label :middle_name, '*Middle Name:' %>
      <%= f.text_field :middle_name %>,

      <%= f.label :last_name, 'Last Name:' %>
      <%= f.text_field :last_name %>,

      <%= f.label :weight, 'Weight (lbs):' %>
      <%= f.select :weight, (0..1000).to_a %>,

      <%= f.label :height, 'Height (cm):' %>
      <%= f.select :height, (0..1000).to_a %>,

      <%= f.label :mrn, '*MRN:' %>
      <%= f.text_field :mrn %>
   </p>
                
   <p>
      <%= submit_tag("Submit") %>
      <%= submit_tag("Cancel") %>
   </p>

   <p> * fields are required </p>
<% end %>

<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing Patients</h1>

<%= link_to 'Add Patient', new_patient_path %><br>
<br>

<table>
   <tr>
      <th>MRN</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3">Actions</th>
   </tr>

   <% @patients.each do |p| %>
      <tr>
         <td><%= p.mrn %></td>
         <td><%= if (p.first_name != "") 
                     p.first_name
                 else
                     "N/A"
                 end %></td>
         <td><%= if (p.last_name != "") 
                     p.last_name
                 else
                     "N/A"
                 end %></td>
         <td><%= link_to 'Show', patient_path(p) %> |</td> 
         <td><%= link_to 'Edit', edit_patient_path(p) %> |</td>
         <td><%= link_to 'Destroy', patient_path(p),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
      </tr>
   <% end %>
</table>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<!-- < % = render 'form' %> -->
<%= form_for :patient, url: patients_path do |f| %>
   <% if @patient.errors.any? %>
      <div id="error_explanation">
         <h2>
            <%= pluralize(@patient.errors.count, "error") %> 
            prohibited this data from being saved:
         </h2>
         <ul>
            <% @patient.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
   <% end %>
<!-- showing information -->
   <p>
      <!-- old... f.label :name, f.text_area :text -->
      <%= f.label :first_name, '*First Name:' %>
      <%= f.text_field :first_name %>,

      <%= f.label :middle_name, '*Middle Name:' %>
      <%= f.text_field :middle_name %>,

      <%= f.label :last_name, 'Last Name:' %>
      <%= f.text_field :last_name %>,

      <%= f.label :weight, 'Weight (lbs):' %>
      <%= f.select :weight, (0..1000).to_a %>,

      <%= f.label :height, 'Height (cm):' %>
      <%= f.select :height, (0..1000).to_a %>,

      <%= f.label :mrn, '*MRN:' %>
      <%= f.text_field :mrn %>
   </p>
                
   <p> * fields are required </p>
   <p>
      <%= submit_tag("Submit") %>
      <%= submit_tag("Cancel") %>
   </p>

<% end %>

<!-- < %= link_to 'Back', patients_path %> -->

app/views/patients/show.html.erb
<b>First Name:</b>
<%= @patient.first_name %>,

<b>Middle Name:</b>
<%= @patient.middle_name %>,

<strong>Last Name:</strong>
<%= @patient.last_name %>,

<b>Weight:</b>
<%= @patient.weight %>,

<b>Height:</b>
<%= @patient.height %>,

<b>MRN:</b>
<%= @patient.mrn %>

<br>
<%= link_to 'Edit', edit_patient_path(@patient) %>

<br>
<h2>Encounters</h2>
 <%= link_to "Add Encounter", new_patient_encounter_path(@patient.id) %>
<br>
<!-- < %= link_to 'encounters/form' %><br> -->
<table>
   <tr>
      <th>Visit Number</th>
      <th>Admitted At</th>
      <th>Discharged At</th>
      <th colspan="3">Actions</th>
   </tr>

   <% @patient.encounters.each do |e| %>
      <tr>
         <td><%= e.visit_number %></td>
         <td><%= e.admitted_at %></td>
         <td><%= e.discharged_at %></td>
         <td><%= link_to 'Show', patient_encounter_path(@patient.id) %> |</td>
         <td><%= link_to 'Edit', edit_patient_encounter_path(@patient.id) %> |</td>
         <td><%= link_to 'Destroy' %></td>
      </tr>
   <% end %>
</table>

<br>
<%= link_to 'Back To All Patients', patients_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>